/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_fxj_jniadddeom01_MathOperation */

#ifndef _Included_com_fxj_jniadddeom01_MathOperation
#define _Included_com_fxj_jniadddeom01_MathOperation
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_fxj_jniadddeom01_MathOperation
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_fxj_jniadddeom01_MathOperation_add
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
